sonar.projectKey=java-pcap
sonar.projectName=Java PCAP - open source
sonar.language=java

sonar.sources=./java-pcap/pcap/src/main
sonar.tests=./java-pcap/pcap/src/test
sonar.java.binaries=./java-pcap/pcap/build/libs/*.jar
